"""
HERMES QC System - Email Sender
Sends the generated Excel summary via Outlook SMTP
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "..", "config", ".env"))


class EmailSender:
    """Send daily QC summary via email"""
    
    def __init__(self, config):
        self.smtp_server = config["smtp_server"]
        self.smtp_port = config["smtp_port"]
        self.sender_email = config["sender_email"]
        self.sender_password = os.getenv("EMAIL_APP_PASSWORD")
        self.recipient = config["recipient_email"]
        self.cc = config.get("cc_email", "")
    
    def build_email_body(self, stats, run_date):
        """Create HTML email body"""
        total = stats.get("total", 0)
        pass_count = stats.get("pass", 0)
        hold_count = stats.get("hold", 0)
        reject_count = stats.get("reject", 0)
        
        # Priority warning
        priority_msg = ""
        if reject_count > 0:
            priority_msg = f"<p style='color:#C00000;font-weight:bold;'>🚨 URGENT: {reject_count} REJECT case(s) need immediate attention.</p>"
        elif hold_count > 0:
            priority_msg = f"<p style='color:#9C5700;font-weight:bold;'>⚠️ {hold_count} HOLD case(s) need vendor follow-up.</p>"
        
        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333;">
            <h2 style="color: #1F4E78;">QC Daily Summary - {run_date.strftime('%d %B %Y')}</h2>
            
            <p>Dear Tanvir,</p>
            
            <p>Please find attached today's consolidated QC inspection summary.</p>
            
            {priority_msg}
            
            <h3 style="color: #1F4E78;">📊 Today's Snapshot</h3>
            <table style="border-collapse: collapse; width: 60%;">
                <tr style="background-color: #1F4E78; color: white;">
                    <th style="padding: 8px; border: 1px solid #ddd;">Metric</th>
                    <th style="padding: 8px; border: 1px solid #ddd;">Count</th>
                </tr>
                <tr><td style="padding: 8px; border: 1px solid #ddd;">Total Reports</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-weight: bold;">{total}</td></tr>
                <tr style="background-color: #C6EFCE;">
                    <td style="padding: 8px; border: 1px solid #ddd;">✅ PASS</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-weight: bold;">{pass_count}</td></tr>
                <tr style="background-color: #FFEB9C;">
                    <td style="padding: 8px; border: 1px solid #ddd;">⚠️ HOLD</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-weight: bold;">{hold_count}</td></tr>
                <tr style="background-color: #FFC7CE;">
                    <td style="padding: 8px; border: 1px solid #ddd;">🔴 REJECT</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-weight: bold;">{reject_count}</td></tr>
            </table>
            
            <h3 style="color: #1F4E78;">📋 Action Items</h3>
            <ol>
                <li>Open the attached Excel file</li>
                <li>Review <b>RED (REJECT)</b> rows first - send urgent CAP request</li>
                <li>Review <b>YELLOW (HOLD)</b> rows - follow up with vendors</li>
                <li>Update CAP Status column as vendors respond</li>
            </ol>
            
            <p style="color: #666; font-size: 11px; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px;">
                Auto-generated by HERMES QC Automation System<br>
                Generated at: {run_date.strftime('%d-%b-%Y %H:%M')}
            </p>
        </body>
        </html>
        """
        return html
    
    def send(self, excel_path, stats, run_date=None):
        """Send email with Excel attachment"""
        if run_date is None:
            run_date = datetime.now()
        
        if not self.sender_password:
            raise ValueError("EMAIL_APP_PASSWORD not set in .env")
        
        msg = MIMEMultipart('alternative')
        msg['From'] = self.sender_email
        msg['To'] = self.recipient
        if self.cc:
            msg['Cc'] = self.cc
        msg['Subject'] = f"QC Daily Summary - {run_date.strftime('%d %B %Y')} | {stats.get('reject',0)}R / {stats.get('hold',0)}H / {stats.get('pass',0)}P"
        
        # HTML body
        html_body = self.build_email_body(stats, run_date)
        msg.attach(MIMEText(html_body, 'html'))
        
        # Attach Excel
        with open(excel_path, 'rb') as f:
            part = MIMEBase('application', 'vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header('Content-Disposition',
                       f'attachment; filename="{Path(excel_path).name}"')
        msg.attach(part)
        
        # Send via SMTP
        recipients = [self.recipient]
        if self.cc:
            recipients.append(self.cc)
        
        with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
            server.starttls()
            server.login(self.sender_email, self.sender_password)
            server.sendmail(self.sender_email, recipients, msg.as_string())
        
        return True


if __name__ == "__main__":
    print("Email sender module loaded successfully")
